function registerAccount()
function registerAccount() { return accessShell('FAST BURG PARA NEGÓCIOS', 'Crie a conta da sua empresa', 'Uma única conta reúne cardápio, pedidos, delivery, impressão e usuários. A primeira unidade operacional é criada automaticamente.', `<form id="registration-form"><label>Seu nome<input name="name" placeholder="Nome do responsável" required></label><label>E-mail de acesso<input name="email" type="email" placeholder="voce@empresa.com" required></label><label>Senha<input name="password" type="password" minlength="8" placeholder="Mínimo de 8 caracteres" required></label><label>Nome da empresa<input name="company" placeholder="Ex.: Grupo Bom Sabor" required></label><label>Link do seu cardápio<input name="slug" id="company-slug" placeholder="Ex.: lanches-da-re" required autocomplete="off"><small>Seu link ficará como <b>fastburg.app/lanches-da-re</b>. Espaços e letras maiúsculas são ajustados automaticamente.</small></label><label>WhatsApp comercial<input name="phone" inputmode="tel" placeholder="(00) 00000-0000"></label>${state.accountError?`<p class="form-error" role="alert">${state.accountError}</p>`:''}${state.accountNotice?`<p class="account-notice">${state.accountNotice}</p>`:''}<button class="primary" type="submit">Criar empresa e iniciar teste <span>→</span></button></form><small class="demo-note">14 dias de teste no plano Starter. Você poderá cadastrar novas unidades quando precisar.</small>`); }document.querySelector('#registration-form')?.addEventListener('submit', registerNewAccount);

  document.querySelector('#company-slug')?.addEventListener('input', event => { event.currentTarget.value = slugify(event.currentTarget.value); });const account = { p_company_name:
    const slug = slugify(form.get('slug'));
    if (slug.length < 3) throw new Error('Escolha um link com pelo menos 3 letras ou números.');
    const account = { p_company_name: form.get('company'), p_restaurant_name: form.get('company'), p_restaurant_slug: slug, p_billing_phone: form.get('phone') || null, p_plan_code: 'starter' };async function loginRestaurant(event)
function slugify(value) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 48); }

import './admin.css';
import './orders.css';
import './platform.css';
import './polish.css';
import { saveRestaurantOrder, signUpAccount, signInAccount, createRestaurantAccount, fetchPlatformCompanies, fetchMyRestaurants, getPendingAccount, savePendingAccount, clearPendingAccount } from './supabase.js';

let products = [
  { id: 1, name: 'Fast Classic', category: 'Burgers', price: 27.9, emoji: '🍔', color: '#f6b849', description: 'Pão brioche, burger de 160g, queijo e molho da casa.', tag: 'Mais pedido' },
  { id: 2, name: 'Duplo Smash', category: 'Burgers', price: 34.9, emoji: '🍔', color: '#e6803e', description: 'Dois burgers smash, cheddar cremoso e cebola caramelizada.', tag: 'Novo' },
  { id: 3, name: 'Chicken Crunch', category: 'Burgers', price: 29.9, emoji: '🍗', color: '#f4c36f', description: 'Frango empanado crocante, coleslaw e maionese defumada.', tag: 'Crocante' },
  { id: 4, name: 'Batata Fast', category: 'Acompanhamentos', price: 16.9, emoji: '🍟', color: '#ffd260', description: 'Batata frita sequinha com páprica e sal da casa.', tag: 'Para dividir' },
  { id: 5, name: 'Onion Rings', category: 'Acompanhamentos', price: 18.9, emoji: '🧅', color: '#eca05d', description: 'Anéis de cebola empanados com molho especial.', tag: '8 unidades' },
  { id: 6, name: 'Coca-Cola lata', category: 'Bebidas', price: 6.5, emoji: '🥤', color: '#d84235', description: 'Coca-Cola gelada 350ml.', tag: '350ml' },
  { id: 7, name: 'Milkshake de Nutella', category: 'Sobremesas', price: 19.9, emoji: '🥛', color: '#8a563d', description: 'Cremoso milkshake de baunilha com Nutella.', tag: '400ml' },
];
products.forEach(product => Object.assign(product, { available: true, printKitchen: true, printCounter: true }));
const extras = [{ id: 'cheddar', name: 'Cheddar extra', price: 4 }, { id: 'bacon', name: 'Bacon crocante', price: 5 }, { id: 'onion', name: 'Cebola caramelizada', price: 3 }];
const seedOrders = [
  { id: '#FB1042', type: 'Mesa 08', items: '2× Fast Classic · 1× Batata Fast', value: 72.7, status: 'Em preparo', time: '4 min', customer: 'Mesa 08', phone: '' },
  { id: '#FB1041', type: 'Delivery', items: '1× Duplo Smash · 1× Coca-Cola lata', value: 41.4, status: 'Novo', time: 'agora', customer: 'Mariana Oliveira', phone: '11988881234', address: 'Rua das Flores, 245 - Centro' },
  { id: '#FB1039', type: 'Mesa 12', items: '2× Chicken Crunch', value: 59.8, status: 'Pronto', time: '12 min', customer: 'Mesa 12', phone: '' },
];
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const price = n => money.format(n);
const mode = new URLSearchParams(location.search).get('modo');
const entryScreens = { vendas: 'landing', cadastro: 'register', restaurante: 'admin-login', gestao: 'platform-login' };
let state = { screen: entryScreens[mode] || 'home', orderType: '', table: '', customer: {}, cart: [], category: 'Todos', selected: null, quantity: 1, selectedExtras: [], orderSent: false, orderNotice: '', checkoutError: '', adminTab: 'pedidos', orders: [...seedOrders], printers: { kitchen: 'pdf', delivery: 'pdf' }, adminProduct: null, orderDetail: null, accountStep: 'identity', accountError: '', accountNotice: '', platformCompanies: [], platformMessage: '', activeRestaurant: null };
const total = () => state.cart.reduce((sum, item) => sum + item.quantity * item.price, 0);
const count = () => state.cart.reduce((sum, item) => sum + item.quantity, 0);

function render() { document.querySelector('#app').innerHTML = ({ home, landing, dine: tableAccess, delivery: deliveryAccess, 'admin-login': adminLogin, admin, menu: customerMenu, register: registerAccount, 'platform-login': platformLogin, platform: platform })[state.screen](); bind(); }
function home() { return `<main class="welcome"><section class="brand-panel"><div class="floating f1">🍔</div><div class="floating f2">🍟</div><div class="brand-mark">FAST<br><span>BURG</span></div><p>Feito rápido.<br>Feito do seu jeito.</p></section><section class="access-panel"><div class="access-copy"><span class="eyebrow">BEM-VINDO</span><h1>Como você quer pedir?</h1><p>Escolha uma opção para ver o cardápio e montar seu pedido.</p></div><div class="order-types"><button data-screen="dine"><span>🍽️</span><div><b>Consumir no local</b><small>Peça e receba na sua mesa</small></div><i>→</i></button><button data-screen="delivery"><span>🛵</span><div><b>Delivery</b><small>Receba onde você estiver</small></div><i>→</i></button></div></section></main>`; }
function landing() { return `<main class="sales"><header><a class="logo">FAST <span>BURG</span></a><span>Sistema para restaurantes</span></header><section class="sales-hero"><div><span class="eyebrow">OPERAÇÃO SIMPLES. RESULTADO REAL.</span><h1>Seu restaurante no controle, do pedido à entrega.</h1><p>Cardápio digital, delivery, painel de produção, impressão de comandas e WhatsApp em um único sistema.</p><button class="primary" data-screen="register">Quero conhecer a Fast Burg <span>→</span></button></div><div class="sales-card"><b>Hoje na operação</b><div><span>🛍️ 12 pedidos</span><small>em tempo real</small></div><div><span>🍳 4 em preparo</span><small>cozinha organizada</small></div><div><span>💬 8 mensagens</span><small>clientes atualizados</small></div></div></section><section class="sales-features"><article><b>🧾</b><h2>Pedidos sem ruído</h2><p>Salão, delivery e produção unidos em uma rotina clara.</p></article><article><b>🖨️</b><h2>Comandas inteligentes</h2><p>Configure cozinha e balcão, com impressão certa por item.</p></article><article><b>📈</b><h2>Cresça com controle</h2><p>Unidades, usuários, licenças e indicadores em uma plataforma.</p></article></section></main>`; }
function accessShell(eyebrow, title, text, form) { return `<main class="access-single"><header><button class="back" data-screen="home">← Voltar</button><a class="logo">FAST <span>BURG</span></a></header><section class="access-panel"><div class="access-copy"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div>${form}</section></main>`; }
function tableAccess() { return accessShell('PEDIDO NO SALÃO', 'Qual é a sua mesa?', 'Digite o código informado pelo atendimento.', `<form id="table-form"><label>Código da mesa</label><input id="table" inputmode="numeric" maxlength="4" placeholder="Ex.: 24" autofocus><button class="primary">Acessar cardápio <span>→</span></button></form>`); }
function deliveryAccess() { return accessShell('PEDIDO DELIVERY', 'Para onde vamos?', 'Informe seus dados para entregar seu pedido com segurança.', `<form id="delivery-form"><label>Seu nome</label><input id="name" placeholder="Como podemos te chamar?" required><label>WhatsApp</label><input id="phone" inputmode="tel" placeholder="(00) 00000-0000" required><label>Endereço de entrega</label><input id="address" placeholder="Rua, número e bairro" required><button class="primary">Ver cardápio <span>→</span></button></form>`); }
function customerMenu() { const categories = ['Todos', ...new Set(products.map(p => p.category))], list = products.filter(p => state.category === 'Todos' || p.category === state.category), location = state.orderType === 'dine' ? `Mesa <b>${state.table}</b>` : '🛵 Delivery'; return `<main class="menu-page"><header><a class="logo">FAST <span>BURG</span></a><div class="table-badge">${location}</div><button class="cart-button" data-cart>🛍️ <i>${count()}</i></button></header><section class="hero"><div><span class="eyebrow">${state.orderType === 'dine' ? 'FOME DETECTADA' : 'DELIVERY FAST BURG'}</span><h1>Seu pedido começa aqui.</h1><p>${state.orderType === 'dine' ? 'Monte do seu jeito e nós levamos até sua mesa.' : `Entregamos em ${state.customer.address}.`}</p></div><div class="hero-art">🍔<span>feito<br>na hora</span></div></section><nav class="categories">${categories.map(c => `<button class="${c === state.category ? 'active' : ''}" data-category="${c}">${c}</button>`).join('')}</nav><section class="products"><div class="section-title"><h2>${state.category === 'Todos' ? 'Destaques do dia' : state.category}</h2><span>${list.length} opções</span></div><div class="grid">${list.map(card).join('')}</div></section>${state.selected ? productModal() : ''}${count() && !state.orderSent ? cartBar() : ''}${state.orderSent ? success() : ''}</main>`; }
function card(p) { return `<article class="product-card" data-product="${p.id}"><div class="food-image" style="--food:${p.color}"><span>${p.emoji}</span><b>${p.tag}</b></div><div class="product-info"><h3>${p.name}</h3><p>${p.description}</p><div><strong>${price(p.price)}</strong><button class="round-add">+</button></div></div></article>`; }
function productModal() { const p = state.selected; return `<div class="overlay"><section class="modal"><button class="close" data-close>×</button><div class="modal-food" style="--food:${p.color}">${p.emoji}</div><span class="eyebrow">${p.category}</span><h2>${p.name}</h2><p>${p.description}</p><div class="extras"><h3>Deixe do seu jeito <small>opcional</small></h3>${extras.map(e => `<label><input type="checkbox" data-extra="${e.id}" ${state.selectedExtras.includes(e.id) ? 'checked' : ''}><span>${e.name}</span><b>+ ${price(e.price)}</b></label>`).join('')}</div><div class="modal-footer"><div class="quantity"><button data-qty="-">−</button><b>${state.quantity}</b><button data-qty="+">+</button></div><button id="add-cart" class="primary">Adicionar · ${price(itemPrice())}</button></div></section></div>`; }
function itemPrice() { return (state.selected.price + state.selectedExtras.reduce((s,id) => s + extras.find(e => e.id === id).price, 0)) * state.quantity; }
function cartBar() { return `<button class="cart-bar" data-cart><span>🛍️ ${count()} ${count() === 1 ? 'item' : 'itens'}</span><b>Ver pedido · ${price(total())}</b></button>`; }
function cartModal() { return `<div class="overlay"><section class="modal cart-modal"><button class="close" data-close>×</button><span class="eyebrow">SEU PEDIDO</span><h2>Quase lá!</h2><div class="cart-items">${state.cart.map((i,n) => `<div class="cart-item"><div class="cart-icon">${i.emoji}</div><div><h3>${i.name} <small>× ${i.quantity}</small></h3><p>${i.extraNames || 'Sem adicionais'}</p><b>${price(i.quantity * i.price)}</b></div><button data-remove="${n}">×</button></div>`).join('')}</div><div class="total"><span>Total</span><b>${price(total())}</b></div>${state.orderType === 'delivery' ? `<div class="delivery-summary">🛵 Entregar para <b>${state.customer.name}</b><br><small>${state.customer.address}</small></div>` : ''}${state.checkoutError?`<p class="form-error">${state.checkoutError}</p>`:''}<button class="primary" id="checkout">Confirmar pedido <span>→</span></button></section></div>`; }
function success() { return `<div class="overlay"><section class="modal success"><div class="success-icon">✓</div><span class="eyebrow">${state.orderNotice ? 'PEDIDO EM MODO DEMONSTRAÇÃO' : 'PEDIDO ENVIADO'}</span><h2>Agora é só curtir.</h2><p>${state.orderNotice || (state.orderType === 'dine' ? `Seu pedido foi enviado à cozinha e será entregue na mesa <b>${state.table}</b>.` : 'Recebemos seu pedido e logo atualizaremos você pelo WhatsApp.')}</p><div class="order-code">Pedido <b>#FB${Math.floor(1000 + Math.random() * 8999)}</b></div><button class="primary" id="new-order">Fazer novo pedido</button></section></div>`; }
function adminLogin() { return accessShell('GESTÃO FAST BURG', 'Acesso do restaurante', 'Entre para acompanhar pedidos, vendas e disponibilidade do cardápio.', `<form id="admin-form"><label>E-mail<input name="email" type="email" placeholder="gestor@fastburg.com" required></label><label>Senha<input name="password" type="password" placeholder="••••••••" required></label>${state.accountError?`<p class="form-error">${state.accountError}</p>`:''}<button class="primary">Entrar no painel <span>→</span></button></form><small class="demo-note">Use o e-mail e senha cadastrados para a sua empresa.</small>`); }
function registerAccount() { return accessShell('FAST BURG PARA NEGÓCIOS', 'Crie a conta da sua empresa', 'Uma única conta reúne cardápio, pedidos, delivery, impressão e usuários. A primeira unidade operacional é criada automaticamente.', `<form id="registration-form"><label>Seu nome<input name="name" placeholder="Nome do responsável" required></label><label>E-mail de acesso<input name="email" type="email" placeholder="voce@empresa.com" required></label><label>Senha<input name="password" type="password" minlength="8" placeholder="Mínimo de 8 caracteres" required></label><label>Nome da empresa<input name="company" placeholder="Ex.: Grupo Bom Sabor" required></label><label>Endereço do cardápio<input name="slug" placeholder="ex.: grupo-bom-sabor" pattern="[a-z0-9-]+" required><small>Use letras minúsculas, números e hífens. Você poderá configurar o cardápio depois.</small></label><label>WhatsApp comercial <input name="phone" placeholder="(00) 00000-0000"></label>${state.accountError?`<p class="form-error">${state.accountError}</p>`:''}${state.accountNotice?`<p class="account-notice">${state.accountNotice}</p>`:''}<button class="primary">Criar empresa e iniciar teste <span>→</span></button></form><small class="demo-note">14 dias de teste no plano Starter. Você poderá cadastrar novas unidades quando precisar.</small>`); }
function platformLogin() { return accessShell('GESTÃO DA PLATAFORMA', 'Controle da Fast Burg', 'Acesse empresas, restaurantes, licenças e faturamento da plataforma.', `<form id="platform-login-form"><label>E-mail do administrador<input name="email" type="email" required></label><label>Senha<input name="password" type="password" required></label>${state.accountError?`<p class="form-error">${state.accountError}</p>`:''}<button class="primary">Entrar na gestão <span>→</span></button></form><small class="demo-note">Seu usuário precisa estar marcado em restaurant_platform_admins no Supabase.</small>`); }
function platform() { const companies=state.platformCompanies, active=companies.filter(c=>c.status==='active'||c.status==='trial'), mrr=companies.reduce((sum,c)=>sum+(c.restaurant_licenses?.[0]?.monthly_price||0),0); return `<main class="platform"><aside><a class="logo">FAST <span>BURG</span></a><p>GESTÃO DA PLATAFORMA<br><small>Visão global do negócio</small></p><nav><button class="selected">▦ Visão geral</button><button>▣ Empresas <i>${companies.length}</i></button><button>◈ Licenças</button><button>▤ Cobranças</button></nav><button class="logout" data-screen="home">Sair</button></aside><section class="platform-content"><header><div><span class="eyebrow">OPERAÇÃO SAAS</span><h1>Visão geral</h1></div><button class="primary" data-screen="register">Nova conta <span>+</span></button></header>${state.platformMessage?`<p class="platform-note">${state.platformMessage}</p>`:''}<div class="platform-metrics"><article><span>Empresas ativas</span><b>${active.length}</b><small>de ${companies.length} cadastradas</small></article><article><span>Receita mensal</span><b>${price(mrr)}</b><small>licenças ativas e trial</small></article><article><span>Restaurantes</span><b>${companies.reduce((s,c)=>s+(c.restaurant_restaurants?.length||0),0)}</b><small>unidades na plataforma</small></article></div><section class="company-list"><div><h2>Empresas e licenças</h2><button id="refresh-platform">Atualizar dados</button></div>${companies.length?companies.map(company=>`<article><div><b>${company.trade_name||company.legal_name}</b><small>${company.billing_email||'Sem e-mail financeiro'} · ${company.restaurant_restaurants?.map(r=>r.name).join(', ')||'Sem unidade'}</small></div><div><span class="license-status ${company.status}">${company.status==='trial'?'Em teste':company.status==='active'?'Ativa':company.status}</span><b>${price(company.restaurant_licenses?.[0]?.monthly_price||0)}/mês</b></div></article>`).join(''):'<p class="empty-platform">Nenhuma empresa carregada. Confirme que seu usuário está em `restaurant_platform_admins` e clique em atualizar.</p>'}</section></section></main>`; }
function admin() { const active = state.orders.map((order,index)=>({...order,index})).filter(o => o.status !== 'Entregue'), revenue = state.orders.reduce((s,o) => s + o.value,0), title = state.adminTab === 'pedidos' ? 'Pedidos em andamento' : state.adminTab === 'cardapio' ? 'Cardápio e disponibilidade' : state.adminTab === 'impressoras' ? 'Impressoras e comandas' : 'Visão geral de hoje'; return `<main class="admin"><aside><a class="logo">FAST <span>BURG</span></a><p class="admin-store">FAST BURG<br><small>Loja aberta · 11:00–23:30</small></p><nav><button class="${state.adminTab==='pedidos'?'selected':''}" data-admin-tab="pedidos">▣ Pedidos <i>${active.length}</i></button><button class="${state.adminTab==='cardapio'?'selected':''}" data-admin-tab="cardapio">☰ Cardápio</button><button class="${state.adminTab==='impressoras'?'selected':''}" data-admin-tab="impressoras">▤ Impressoras</button><button class="${state.adminTab==='visao'?'selected':''}" data-admin-tab="visao">◔ Visão geral</button></nav><button class="logout" data-screen="home">Sair</button></aside><section class="admin-content"><header><div><span class="eyebrow">PAINEL DO RESTAURANTE</span><h1>${title}</h1></div><div class="live"><i></i> Atualização ao vivo</div></header>${state.adminTab==='pedidos' ? ordersPanel(active) : state.adminTab==='cardapio' ? menuPanel() : state.adminTab==='impressoras' ? printersPanel() : overviewPanel(revenue, active.length)}</section>${state.adminProduct ? productAdminModal() : ''}${state.orderDetail !== null ? orderDetailModal() : ''}</main>`; }
function ordersPanel(orders) { const stages=['Novo','Em preparo','Pronto']; return `<div class="order-board">${stages.map(stage=>{const list=orders.filter(order=>order.status===stage);return `<section class="order-column"><header><h2>${stage}</h2><span>${list.length}</span></header><div>${list.length?list.map(order=>orderCard(order)).join(''):'<p class="empty-order">Nenhum pedido nesta etapa.</p>'}</div></section>`}).join('')}</div>`; }
function orderCard(o) { return `<article class="order-card" data-order="${o.index}"><div class="order-card-top"><b>${o.id}</b><span class="pill ${o.status.toLowerCase().replace(' ','-')}">${o.type}</span></div><h3>${o.customer || o.type}</h3><p>${o.items}</p><small>◷ ${o.time} · ${price(o.value)}</small><div class="card-actions">${o.phone?'<button class="whatsapp" data-whatsapp="'+o.index+'">WhatsApp</button>':''}${o.status !== 'Pronto'?`<button data-advance="${o.index}">${nextLabel(o.status)} →</button>`:`<button data-advance="${o.index}">Entregar ✓</button>`}</div></article>`; }
function nextLabel(status) { return status==='Novo'?'Aceitar':'Marcar pronto'; }
function menuPanel() { return `<div class="menu-admin-header"><p>Cadastre produtos, altere preços, disponibilidade e para quais comandas cada item deve seguir.</p><button class="primary" data-new-product>Novo produto <span>+</span></button></div><div class="admin-menu-grid">${products.map(p => `<article data-admin-product="${p.id}"><div class="mini-food" style="--food:${p.color}">${p.emoji}</div><div><b>${p.name}</b><small>${price(p.price)} · ${p.available ? 'Disponível' : 'Pausado'}</small></div><span class="route-dots">${p.printKitchen?'🍳':''}${p.printCounter?'🧾':''}</span></article>`).join('')}</div>`; }
function productAdminModal() { const p = state.adminProduct === 'new' ? { name:'', category:'Burgers', price:'', emoji:'🍔', description:'', tag:'Novo', available:true, printKitchen:true, printCounter:true } : products.find(product => product.id === state.adminProduct), categories=['Burgers','Acompanhamentos','Bebidas','Sobremesas'], icons=['🍔','🍟','🍗','🥤','🥛','🧅']; return `<div class="overlay"><section class="modal admin-modal"><button class="close" data-close-admin>×</button><div class="modal-heading"><span class="eyebrow">${state.adminProduct==='new'?'NOVO PRODUTO':'EDITAR PRODUTO'}</span><h2>${state.adminProduct==='new'?'Cadastrar item do cardápio':'Configurar '+p.name}</h2><p>Defina como o item aparece para o cliente e para a operação.</p></div><form id="product-form"><fieldset><legend>Informações do produto</legend><label>Nome do produto<input name="name" value="${p.name}" placeholder="Ex.: Smash Bacon" required></label><div class="form-pair"><label>Categoria<select name="category">${categories.map(category=>`<option ${category===p.category?'selected':''}>${category}</option>`).join('')}</select></label><label>Preço de venda<input name="price" type="number" step="0.01" min="0" value="${p.price}" placeholder="0,00" required></label></div><div class="form-pair"><label>Ícone do cardápio<select name="emoji">${icons.map(icon=>`<option ${icon===p.emoji?'selected':''}>${icon}</option>`).join('')}</select></label><label>Etiqueta <input name="tag" value="${p.tag||''}" placeholder="Ex.: Mais pedido"></label></div><label>Descrição para o cliente<input name="description" value="${p.description}" placeholder="Conte o que acompanha o produto" required></label></fieldset><fieldset class="routing"><legend>Operação e impressão</legend><p>Escolha onde este produto deve constar quando um pedido for confirmado.</p><label class="setting-row"><span><b>🍳 Comanda da cozinha</b><small>Itens que precisam de preparo</small></span><input name="printKitchen" type="checkbox" ${p.printKitchen?'checked':''}></label><label class="setting-row"><span><b>🧾 Via balcão / delivery</b><small>Itens para conferência e expedição</small></span><input name="printCounter" type="checkbox" ${p.printCounter?'checked':''}></label></fieldset><label class="availability"><input name="available" type="checkbox" ${p.available?'checked':''}><span><b>Produto disponível</b><small>Exibir para os clientes no cardápio digital</small></span></label><button class="primary">${state.adminProduct==='new'?'Cadastrar produto':'Salvar alterações'} <span>→</span></button></form></section></div>`; }
function orderDetailModal() { const o = state.orders[state.orderDetail]; return `<div class="overlay"><section class="modal admin-modal"><button class="close" data-close-order>×</button><span class="eyebrow">CONFERÊNCIA DO PEDIDO</span><h2>${o.id} · ${o.type}</h2><div class="order-detail"><div><small>Status atual</small><b class="pill ${o.status.toLowerCase().replace(' ','-')}">${o.status}</b></div><div><small>Recebido</small><b>Há ${o.time}</b></div>${o.address?`<div><small>Entrega</small><p>${o.address}</p></div>`:''}<div><small>Itens</small><p>${o.items}</p></div><div><small>Destino de impressão</small><p>🍳 Cozinha ${o.type==='Delivery'?'· 🧾 Balcão/delivery':''}</p></div><div class="total"><span>Total do pedido</span><b>${price(o.value)}</b></div></div>${o.phone?`<button class="whatsapp-full" data-whatsapp="${state.orderDetail}">💬 Enviar atualização pelo WhatsApp</button>`:''}<button class="primary" data-detail-advance>${o.status==='Novo'?'Aceitar pedido':o.status==='Em preparo'?'Marcar como pronto':'Confirmar entrega'} <span>→</span></button></section></div>`; }
function printersPanel() { return `<div class="printer-intro"><span>Configure para onde cada tipo de comanda será enviado. Em teste, escolha <b>Salvar como PDF</b> para abrir a janela de impressão do navegador.</span></div><div class="printer-grid"><article class="printer-card"><div class="printer-icon">👨‍🍳</div><div><span class="eyebrow">VIA COZINHA</span><h2>Produção</h2><p>Itens, adicionais, observações e número da mesa.</p></div><label>Destino da impressão<select data-printer="kitchen"><option value="pdf" ${state.printers.kitchen==='pdf'?'selected':''}>Salvar como PDF (teste)</option><option value="elgin-cozinha" ${state.printers.kitchen==='elgin-cozinha'?'selected':''}>Elgin 80 mm - Cozinha</option><option value="system">Escolher no sistema</option></select></label><button class="primary" data-print-test="kitchen">Imprimir teste da cozinha <span>→</span></button></article><article class="printer-card"><div class="printer-icon delivery-icon">🛵</div><div><span class="eyebrow">VIA DELIVERY / CAIXA</span><h2>Expedição</h2><p>Cliente, endereço, pagamento, itens e total.</p></div><label>Destino da impressão<select data-printer="delivery"><option value="pdf" ${state.printers.delivery==='pdf'?'selected':''}>Salvar como PDF (teste)</option><option value="elgin-delivery" ${state.printers.delivery==='elgin-delivery'?'selected':''}>Elgin 80 mm - Delivery</option><option value="system">Escolher no sistema</option></select></label><button class="primary" data-print-test="delivery">Imprimir teste do delivery <span>→</span></button></article></div><section class="print-flow"><b>Como testar agora</b><ol><li>Selecione “Salvar como PDF”.</li><li>Clique em “Imprimir teste”.</li><li>Na janela do navegador, selecione “Salvar como PDF” e confirme.</li></ol><small>Quando a Elgin estiver conectada, o agente local permitirá selecionar a impressora física e imprimir sem abrir essa janela.</small></section>`; }
function overviewPanel(revenue, active) { return `<div class="metrics"><article><span>Vendas hoje</span><b>${price(revenue + 483.4)}</b><small>↑ 12% vs. ontem</small></article><article><span>Pedidos hoje</span><b>38</b><small>↑ 8% vs. ontem</small></article><article><span>Em andamento</span><b>${active}</b><small>Atualizado agora</small></article></div><section class="chart-placeholder"><h2>Horários com mais pedidos</h2><div class="bars">${[35,52,68,45,92,75,56,82,60].map((h,i)=>`<i style="height:${h}%"><small>${12+i}h</small></i>`).join('')}</div></section>`; }
function bind() {
  document.querySelectorAll('[data-screen]').forEach(b => b.onclick=()=>{ state.screen=b.dataset.screen; render(); });
  document.querySelector('#registration-form')?.addEventListener('submit', registerNewAccount);
  document.querySelector('#platform-login-form')?.addEventListener('submit', loginPlatform);
  document.querySelector('#admin-form')?.addEventListener('submit', loginRestaurant);
  document.querySelector('#refresh-platform')?.addEventListener('click', loadPlatformCompanies);
  document.querySelector('#table-form')?.addEventListener('submit', e=>{e.preventDefault();const v=document.querySelector('#table').value.trim();if(v){state.table=v;state.orderType='dine';state.screen='menu';render();}});
  document.querySelector('#delivery-form')?.addEventListener('submit', e=>{e.preventDefault();state.customer={name:document.querySelector('#name').value,address:document.querySelector('#address').value,phone:document.querySelector('#phone').value};state.orderType='delivery';state.screen='menu';render();});
  document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;render();}); document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{state.selected=products.find(p=>p.id===Number(b.dataset.product));state.quantity=1;state.selectedExtras=[];render();});
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{state.selected=null;render();}); document.querySelectorAll('[data-extra]').forEach(i=>i.onchange=()=>{const id=i.dataset.extra;state.selectedExtras=i.checked?[...state.selectedExtras,id]:state.selectedExtras.filter(x=>x!==id);render();}); document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{state.quantity=Math.max(1,state.quantity+Number(b.dataset.qty));render();});
  document.querySelector('#add-cart')?.addEventListener('click',()=>{const p=state.selected;state.cart.push({...p,quantity:state.quantity,price:p.price+state.selectedExtras.reduce((s,id)=>s+extras.find(e=>e.id===id).price,0),extraNames:state.selectedExtras.map(id=>extras.find(e=>e.id===id).name).join(', ')});state.selected=null;render();});
  document.querySelectorAll('[data-cart]').forEach(b=>b.onclick=openCart); document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart.splice(Number(b.dataset.remove),1);openCart();}); document.querySelector('#checkout')?.addEventListener('click', submitOrder);document.querySelector('#new-order')?.addEventListener('click',()=>{state.cart=[];state.orderSent=false;state.orderNotice='';state.checkoutError='';render();});
  document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>{state.adminTab=b.dataset.adminTab;render();});document.querySelectorAll('[data-advance]').forEach(b=>b.onclick=event=>{event.stopPropagation();const o=state.orders[Number(b.dataset.advance)];o.status=o.status==='Novo'?'Em preparo':o.status==='Em preparo'?'Pronto':'Entregue';render();});
  document.querySelectorAll('[data-printer]').forEach(select=>select.onchange=()=>{state.printers[select.dataset.printer]=select.value;}); document.querySelectorAll('[data-print-test]').forEach(button=>button.onclick=()=>printTestTicket(button.dataset.printTest));
  document.querySelector('[data-new-product]')?.addEventListener('click',()=>{state.adminProduct='new';render();}); document.querySelectorAll('[data-admin-product]').forEach(item=>item.onclick=()=>{state.adminProduct=Number(item.dataset.adminProduct);render();}); document.querySelectorAll('[data-order]').forEach(item=>item.onclick=event=>{if(!event.target.closest('[data-advance]')){state.orderDetail=Number(item.dataset.order);render();}});
  document.querySelector('[data-close-admin]')?.addEventListener('click',()=>{state.adminProduct=null;render();}); document.querySelector('[data-close-order]')?.addEventListener('click',()=>{state.orderDetail=null;render();}); document.querySelector('#product-form')?.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget), id=state.adminProduct==='new'?Date.now():state.adminProduct, original=products.find(product=>product.id===id)||{};const product={...original,id,name:form.get('name'),category:form.get('category'),price:Number(form.get('price')),emoji:form.get('emoji'),color:original.color||'#f6b849',description:form.get('description'),tag:form.get('tag')||'Novo',available:form.has('available'),printKitchen:form.has('printKitchen'),printCounter:form.has('printCounter')};if(state.adminProduct==='new')products=[...products,product];else products=products.map(item=>item.id===id?product:item);state.adminProduct=null;render();}); document.querySelector('[data-detail-advance]')?.addEventListener('click',()=>{const order=state.orders[state.orderDetail];order.status=order.status==='Novo'?'Em preparo':order.status==='Em preparo'?'Pronto':'Entregue';state.orderDetail=null;render();}); document.querySelectorAll('[data-whatsapp]').forEach(button=>button.onclick=event=>{event.stopPropagation();openWhatsApp(state.orders[Number(button.dataset.whatsapp)]);});
}
function openWhatsApp(order) { const stageText = order.status==='Novo'?'Recebemos seu pedido e ele já entrou na fila de preparo.':order.status==='Em preparo'?'Seu pedido está sendo preparado com muito cuidado.':order.status==='Pronto'?'Seu pedido está pronto e sairá para entrega em breve.':'Seu pedido foi entregue. Esperamos que aproveite!'; const message = `Olá, ${order.customer}! 🍔\n\nPedido ${order.id}: ${stageText}\n\n${order.type==='Delivery'?'Endereço: '+order.address+'\n\n':''}Fast Burg agradece seu pedido!`; window.open(`https://wa.me/55${order.phone}?text=${encodeURIComponent(message)}`, '_blank', 'noopener'); }
function openCart(){document.querySelectorAll('.overlay').forEach(x=>x.remove());document.querySelector('.menu-page').insertAdjacentHTML('beforeend',cartModal());bind();}
function printTestTicket(destination) {
  const kitchen = destination === 'kitchen';
  const content = kitchen ? `<h1>FAST BURG</h1><h2>VIA COZINHA - TESTE</h2><hr><b>#FB1042 &nbsp; MESA 08</b><h3>2x Fast Classic</h3><p>- Cheddar extra<br>- Bacon crocante</p><h3>1x Batata Fast</h3><p>- Sem sal</p><hr><b>PREPARAR E ENTREGAR NA MESA 08</b>` : `<h1>FAST BURG</h1><h2>VIA DELIVERY / CAIXA - TESTE</h2><hr><b>#FB1043 - DELIVERY</b><h3>Mariana Oliveira</h3><p>WhatsApp: (11) 98888-1234<br>Rua das Flores, 245 - Apto 32 - Centro</p><hr><h3>1x Duplo Smash - R$ 34,90</h3><p>+ Cheddar extra</p><h3>1x Coca-Cola lata - R$ 6,50</h3><hr><h2>TOTAL: R$ 45,40</h2><b>PAGAMENTO: PIX</b>`;
  const win = window.open('', '_blank', 'width=420,height=700');
  if (!win) return alert('Permita pop-ups para abrir a comanda de teste.');
  win.document.write(`<!doctype html><html><head><title>Comanda teste</title><style>@page{size:80mm auto;margin:4mm}body{font-family:Arial,sans-serif;width:72mm;margin:0;font-size:12px}h1{text-align:center;margin:0;background:#f15b23;color:#fff;padding:10px;font-size:22px}h2{text-align:center;font-size:14px}h3{font-size:14px;margin:14px 0 4px}p{line-height:1.45;margin:0 0 10px}hr{border:0;border-top:1px dashed #222;margin:14px 0}</style></head><body>${content}<script>window.onload=()=>window.print()<\/script></body></html>`);
  win.document.close();
}
async function submitOrder() {
  const button = document.querySelector('#checkout');
  button.disabled = true;
  button.textContent = 'Enviando pedido...';
  state.checkoutError = '';
  try {
    const result = await saveRestaurantOrder({
      p_restaurant_slug: state.activeRestaurant?.slug || 'fast-burg',
      p_channel: state.orderType === 'dine' ? 'dine_in' : 'delivery',
      p_table_code: state.orderType === 'dine' ? state.table : null,
      p_customer_name: state.customer.name || null,
      p_customer_phone: state.customer.phone || null,
      p_delivery_address: state.customer.address ? { address: state.customer.address } : {},
      p_items: state.cart.map(item => ({ product_id: item.remoteId, quantity: item.quantity, notes: item.extraNames || null, addon_ids: item.addonIds || [] })),
    });
    state.orderNotice = result.offline ? 'Este pedido foi confirmado apenas no modo de demonstração. Cadastre e conecte os produtos do restaurante para enviá-lo à operação real.' : '';
    state.orderSent = true;
    render();
  } catch (error) {
    state.checkoutError = `Não foi possível enviar o pedido: ${error.message}`;
    openCart();
  }
}
async function registerNewAccount(event) {
  event.preventDefault();
  const form = new FormData(event.currentTarget);
  const button = event.currentTarget.querySelector('button[type="submit"]');
  button.disabled = true; button.textContent = 'Criando conta...'; state.accountError = ''; state.accountNotice = '';
  try {
    const account = { p_company_name: form.get('company'), p_restaurant_name: form.get('company'), p_restaurant_slug: form.get('slug'), p_billing_phone: form.get('phone') || null, p_plan_code: 'starter' };
    savePendingAccount(account);
    const registration = await signUpAccount({ name: form.get('name'), email: form.get('email'), password: form.get('password') });
    if (!registration.session) {
      state.accountNotice = 'Conta criada. Confirme o e-mail enviado pelo Supabase e depois entre em “Acesso do restaurante” para concluir a criação da empresa.';
      render(); return;
    }
    await createRestaurantAccount(account); clearPendingAccount();
    state.screen = 'admin'; state.accountError = ''; render();
  } catch (error) { state.accountError = error.message; render(); }
}
async function loginRestaurant(event) {
  event.preventDefault(); const form = new FormData(event.currentTarget); state.accountError = '';
  try {
    await signInAccount({ email: form.get('email'), password: form.get('password') });
    let restaurants = await fetchMyRestaurants();
    const pending = getPendingAccount();
    if (!restaurants.length && pending) { await createRestaurantAccount(pending); clearPendingAccount(); restaurants = await fetchMyRestaurants(); }
    if (!restaurants.length) throw new Error('Este usuário não possui acesso a nenhuma empresa. Crie uma conta pela página de vendas ou peça acesso ao administrador.');
    state.activeRestaurant = restaurants[0].restaurant_restaurants; state.screen='admin'; render();
  }
  catch (error) { state.accountError=error.message; render(); }
}
async function loginPlatform(event) {
  event.preventDefault();
  const form = new FormData(event.currentTarget); state.accountError = '';
  try { await signInAccount({ email: form.get('email'), password: form.get('password') }); state.screen='platform'; await loadPlatformCompanies(); }
  catch (error) { state.accountError=error.message; render(); }
}
async function loadPlatformCompanies() {
  state.platformMessage = 'Carregando dados da plataforma...'; render();
  try { state.platformCompanies = await fetchPlatformCompanies(); state.platformMessage = state.platformCompanies.length ? '' : 'Nenhuma empresa foi encontrada para este administrador.'; }
  catch (error) { state.platformMessage = error.message; }
  render();
}
render();
